version: "3.8"

services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2_container
    runtime: runc
    volumes:
      - ../:/workspace
    network_mode: host
    stdin_open: true
    tty: true